<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
        <ProjectReference Include="..\MinBlazor.Core\MinBlazor.Core.csproj" />
    <ProjectReference Include="..\..\src\MinBlazor\MinBlazor.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.47.0" />
  </ItemGroup>

</Project>

