<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MinBlazor.Core\MinBlazor.Core.csproj" />
    <ProjectReference Include="..\MinBlazor.Compiler\MinBlazor.Compiler.csproj" />
  </ItemGroup>

</Project>
