<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>minblazor</AssemblyName>

    <PackAsTool>true</PackAsTool>
    <ToolCommandName>minblazor</ToolCommandName>
    <PackageId>MinBlazor</PackageId>
    <Version>0.4.0</Version>
    <Authors>andresitomanuel</Authors>
    <Description>Run a single .razor file as a Blazor WebAssembly app.</Description>
    <PackageOutputPath>$(MSBuildThisFileDirectory)../../nupkg</PackageOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MinBlazor.Razor\MinBlazor.Razor.csproj" />
  </ItemGroup>

</Project>
